### ISSUE TITLE
If user goes to http://dk30.io/projects/feed when not logged in stack trace is printed

### ISSUE THREAD

**Issue by GingerNaTT** [BrandonDiaz/DK30-Web#6]
When user goes to http://dk30.io/projects/feed when he is not logged a stack trace is printed out. User should be moved to the main site or asked to log in.

TypeError: Cannot read property '_id' of undefined
    at /var/www/routes/projects.js:63:56
    at Layer.handle [as handle_request] (/var/www/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/www/node_modules/express/lib/router/index.js:174:3)
    at router (/var/www/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/www/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/node_modules/express/lib/router/index.js:317:13)
    at /var/www/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/node_modules/express/lib/router/index.js:275:10)
    at /var/www/node_modules/express/lib/router/index.js:635:15

![image](https://user-images.githubusercontent.com/12325774/38902113-68d0bf18-429f-11e8-83cd-72b59b09b023.png)

**Comment by BrandonDiaz** [comment]
Partially resolved, redirects to homepage for now, but would be better to have an "oops, you aren't logged in"sort of deal in the future.
